OwOifier
swampservers/contrib pull request #37
Opened 2019-07-07 01:56 UTC by chev2

What's This?

2019-07-09 04:44 UTC, swampservers commented on lua/autorun/owoifier.lua
> +				net.Start("OwOSendToggleInfo")
You can just use player:PrintMessage

2019-07-09 04:49 UTC, swampservers commented on lua/autorun/owoifier.lua
> +	for emotecolon in string.gmatch(text, ":%a-:") do //replace swampchat image emotes with text ones, because I cant figure out how to prevent them from being owo-ified
do you mean the r/l being replaced? maybe you could iterate the string one letter at a time and keep a boolean state if the current letter is part of an emote name?

2019-07-11 02:27 UTC, swampservers commented on lua/autorun/owoifier.lua
> +			if string.find(v, "[RrLl]") then --R and L to W
Doing table.remove shifts everything down, then inserting shifts it all back up in O(n) time. Also the Replace parts are overcomplex. You can just:
```
if string.find("RrLl", v) then
if v==v:lower() then
splitstring[k] = "w"
else
splitstring[k] = "W"
end
end
```

2019-07-11 02:28 UTC, swampservers commented on lua/autorun/owoifier.lua
> +		if v == ":" or v == ";" or v == "[" or v == "]" then --Keep emotes and chat colors the same
string.find(":;[]",v)

2019-07-11 02:31 UTC, swampservers commented on lua/autorun/owoifier.lua
> +					table.remove(splitstring, k+1)
just do:
splitstring[k] = "ny"

2019-07-11 02:34 UTC, swampservers commented on lua/autorun/owoifier.lua
> +	if string.StartWith(owotext, "!") then
Case sensitive and works across the whole message, not just the start. I think you can just set isemoteenabled=true if the string starts with a ! before iterating it

2019-07-11 02:34 UTC, swampservers commented on lua/autorun/owoifier.lua
> +	local owotext = string.format(owotext.." %s", OwOemotes[math.random(#OwOemotes)]) --add a random emote at the end
owotext.." "..OwOemotes[]

2019-07-11 02:36 UTC, swampservers commented on lua/autorun/owoifier.lua
> +local OwOemotes = {"OwO", "owo", "UwU", "uwu", "TwT", ">w<", ">wO", "Ow<", ":3c", ":3", ":33", ":333", "nya", "(> owo )>",
all this code is serverside, so it should just be in autorun/server without any SERVER checks

2019-07-11 02:53 UTC, swampservers reviewed
some changes

2019-07-11 04:58 UTC, chev2 commented
I added uppercase support to the n(vowel) to ny(vowel) on top of your comments

2019-07-14 07:00 UTC, swampservers requested changes

2019-07-14 07:00 UTC, swampservers commented on lua/autorun/server/owoifier.lua
> +		elseif ply:GetNWBool("OwOEnabled", false) == true then --Disable OwO
Only used server side, so it can just be a table variable ply.OwOenabled

2019-07-14 07:00 UTC, swampservers commented on lua/autorun/server/owoifier.lua
> +	local owotext = string.gsub(owotext, "this", "dis")
Did you test this? I think redeclaring this might be an error

2019-07-14 07:00 UTC, swampservers commented on lua/autorun/server/owoifier.lua
> +hook.Add("PlayerSay", "ClientOwOToggle", function(ply, text, team)
This should use the chatcommand api I made, look in lua/chatcommands

2019-07-14 20:35 UTC, chev2 commented on lua/autorun/server/owoifier.lua
> +	local owotext = string.gsub(owotext, "this", "dis")
What kind of error are you expecting it to throw? I've tested this in singleplayer and on a dedicated server and it doesn't throw any errors, and doesn't silently fail either

2019-07-15 09:50 UTC, chev2 commented
I left the local "owotext" variable unchanged as it still works fine for me

2019-07-15 18:17 UTC, swampservers commented on lua/autorun/server/owoifier.lua
> +	local owotext = string.gsub(owotext, "this", "dis")
Okay I must have been thinking of a different language

2019-07-15 18:22 UTC, merged