Update devtools structEnvironment paths
swampservers/contrib pull request #409
Opened 2023-09-10 23:35 UTC by swamproyal

2023-10-18 02:05 UTC, WinterPhoenix requested changes
The base `entities` and `weapons` folders should remain

2023-10-18 02:36 UTC, swamproyal commented
> The base `entities` and `weapons` folders should remain

Sounds good, changed.

2023-11-09 05:41 UTC, WinterPhoenix commented
And the base `effects` folder, sorry lol

2024-01-04 01:31 UTC, WinterPhoenix approved these changes

2024-01-04 01:32 UTC, merged